const ramais = [
  
    { nome: "Isaac", departamento: "Administrativo", setor: "Contabilidade", ramal: "3250" },
    { nome: "Sophia", departamento: "Administrativo", setor: "Contabilidade", ramal: "3209" },
    { nome: "Lucas", departamento: "Administrativo", setor: "Desenvolvimento", ramal: "3217" },
    { nome: "Olivia", departamento: "Administrativo", setor: "Analista", ramal: "3217" },
    { nome: "Mateus", departamento: "Administrativo", setor: "Analista", ramal: "3223" },
    { nome: "Alice", departamento: "Administrativo", setor: "Analista", ramal: "3205" },
    { nome: "Davi", departamento: "Administrativo", setor: "Analista", ramal: "3283" },
    { nome: "Manuela", departamento: "Administrativo", setor: "Expediente", ramal: "3242" },
    { nome: "Laura", departamento: "Administrativo", setor: "Expediente", ramal: "3265" },
    { nome: "Arthur", departamento: "Administrativo", setor: "Recepção", ramal: "3269" },
    { nome: "Gabriel", departamento: "Administrativo", setor: "Financeiro", ramal: "3215/ 5777-2244" },
    { nome: "Alice", departamento: "Administrativo", setor: "Financeiro", ramal: "3215/ 5777-2244" },
    { nome: "Laura", departamento: "Administrativo", setor: "Financeiro", ramal: "3215/ 5777-2244" },
    { nome: "Enzo", departamento: "Administrativo", setor: "Financeiro", ramal: "3215" },
    { nome: "Valentina", departamento: "Administrativo", setor: "Assistente", ramal: "3246" },
    { nome: "Sophie", departamento: "Administrativo", setor: "Assistente", ramal: "3207" },
    { nome: "Eloá", departamento: "Administrativo", setor: "Assistente", ramal: "3271" },
    { nome: "Rafael", departamento: "Administrativo", setor: "Recepção", ramal: "3202" },
    { nome: "Pedro", departamento: "Administrativo", setor: "Recepção", ramal: "3272" },
    { nome: "Júlia", departamento: "Administrativo", setor: "Recepção", ramal: "3254" },
    { nome: "Bernardo", departamento: "Administrativo", setor: "Supervisão", ramal: "3214" },
    { nome: "Maria", departamento: "Administrativo", setor: "Supervisão", ramal: "3230" },
    { nome: "Lorenzo", departamento: "Administrativo", setor: "Supervisão", ramal: "3220" },
    { nome: "Miguel", departamento: "Administrativo", setor: "Gerente", ramal: "3230" },
  
 
    { nome: "Lívia", departamento: "Departamento Pessoal", setor: "Recrutamento", ramal: "3208" },
    { nome: "Rafaela", departamento: "Departamento Pessoal", setor: "Recrutamento", ramal: "3225" },
    { nome: "Eduarda", departamento: "Departamento Pessoal", setor: "Analista", ramal: "3219" },
    { nome: "Vitoria", departamento: "Departamento Pessoal", setor: "Conclusão", ramal: "3292" },
    { nome: "Amanda", departamento: "Departamento Pessoal", setor: "Auxiliar", ramal: "3292" },
    { nome: "Gabrielle", departamento: "Departamento Pessoal", setor: "Auxiliar", ramal: "3292" },
    { nome: "Isabela", departamento: "Departamento Pessoal", setor: "Auxiliar", ramal: "3224" },
    { nome: "Gustavo", departamento: "Departamento Pessoal", setor: "Gerente", ramal: "3210" },
    { nome: "Leonardo", departamento: "Departamento Pessoal", setor: "Gerente", ramal: "3284" },
    { nome: "Sophia", departamento: "Departamento Pessoal", setor: "Assistente", ramal: "3253" },
    { nome: "Thiago", departamento: "Departamento Pessoal", setor: "Assistente", ramal: "3204" },
    { nome: "Matheus", departamento: "Departamento Pessoal", setor: "Assistente", ramal: "3282" },
    { nome: "Carlos", departamento: "Departamento Pessoal", setor: "Técnico", ramal: "3285" },
    { nome: "Lara", departamento: "Departamento Pessoal", setor: "Técnico", ramal: "3291" },
    { nome: "Ana", departamento: "Departamento Pessoal", setor: "Técnico", ramal: "3201" },
    { nome: "Letícia", departamento: "Departamento Pessoal", setor: "Analista", ramal: "3201" },
    { nome: "Lucas", departamento: "Departamento Pessoal", setor: "Analista", ramal: "5888-7030" },
    { nome: "Enzo", departamento: "Departamento Pessoal", setor: "Analista", ramal: "5888-7030" },
    { nome: "Pedro", departamento: "Departamento Pessoal", setor: "Conclusão", ramal: "5888-7030" },
    { nome: "Julia", departamento: "Departamento Pessoal", setor: "Conclusão", ramal: "5888-3113" },
    { nome: "Luan", departamento: "Departamento Pessoal", setor: "Conclusão", ramal: "5888-3113" },
 
  { nome: "Lucas", departamento: "Marketing", setor: "Designer", ramal: "3248" },
  { nome: "Daniel", departamento: "Marketing", setor: "Analista", ramal: "3231" },
  { nome: "Maria", departamento: "Marketing", setor: "Copywriter", ramal: "3278" },
  { nome: "Paula", departamento: "Marketing", setor: "Analista", ramal: "3252" },
  { nome: "Nanci", departamento: "Marketing", setor: "Gerente", ramal: "3247" },
 
  { nome: "Carla", departamento: "Comercial", setor: "Vendedor", ramal: "3226" },
  { nome: "Ana Paula", departamento: "Comercial", setor: "Vendedor", ramal: "3263" },
  { nome: "Pedro", departamento: "Comercial", setor: "Assistente", ramal: "3227" },
  { nome: "Nikolas", departamento: "Comercial", setor: "Consultor", ramal: "3227" },
  { nome: "Augusto", departamento: "Comercial", setor: "Atendimento ao cliente", ramal: "3270" },
  { nome: "Luiz Fábio", departamento: "Comercial", setor: "Supervisor", ramal: "3270" },
  { nome: "Kenji", departamento: "Comercial", setor: "Gerente", ramal: "3270" },
 
    { nome: "Isabella", departamento: "Informática", setor: "Analista de Sistemas", ramal:"6540" },
    { nome: "Lucas", departamento: "Informática", setor: "Analista de Sistemas", ramal: "9654" },
    { nome: "Laura", departamento: "Informática", setor: "Desenvolvedor Web", ramal: "2133" },
    { nome: "Gabriel", departamento: "Informática", setor: "Engenheiro de Software", ramal: "5445" },
    { nome: "Sophia", departamento: "Informática", setor: "Analista de Projetos", ramal: "4877" },
    { nome: "Enzo", departamento: "Informática", setor: "Engenheiro de Software", ramal: "3333" },
    { nome: "Valentina", departamento: "Informática", setor: "Desenvolvedor de Aplicações", ramal: "2270" },
    { nome: "Matheus", departamento: "Informática", setor: "Analista de Sistemas", ramal: "4270" },
    { nome: "Isabel", departamento: "Informática", setor: "Desenvolvedor Web", ramal: "3570" },
    { nome: "Gustavo", departamento: "Informática", setor: "Técnico de Suporte", ramal: "3570" },
    { nome: "Helena", departamento: "Informática", setor: "Analista de Sistemas", ramal: "3670" },
    { nome: "Arthur", departamento: "Informática", setor: "Engenheiro de Software", ramal: "3271" },
    { nome: "Maria", departamento: "Informática", setor: "Desenvolvedor de Aplicações", ramal: "3273" },
    { nome: "Daniel", departamento: "Informática", setor: "Analista de Projetos", ramal: "3274" },
    { nome: "João", departamento: "Informática", setor: "Engenheiro de Software", ramal: "3250" },
    { nome: "Bianca", departamento: "Informática", setor: "Analista de Sistemas", ramal: "3276" },
    { nome: "Miguel", departamento: "Informática", setor: "Desenvolvedor Web", ramal: "3277" },
    { nome: "Larissa", departamento: "Informática", setor: "Analista de Sistemas", ramal: "3278" },
    { nome: "Pedro", departamento: "Informática", setor: "Técnico de Suporte", ramal: "3279" },
    { nome: "Amanda", departamento: "Informática", setor: "Técnico de Suporte", ramal: "3222" },
    { nome: "Bruno", departamento: "Informática", setor: "Desenvolvedor Web", ramal: "3472" },
    { nome: "Camila", departamento: "Informática", setor: "Desenvolvedor Web", ramal: "3970" },

];

export default ramais;
